name: Production-Stage

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup project
        run: npm run setup:project -- --type=production

      - name: Deploy project
        run: |
          cd ./production && sudo docker compose up -d --build docs-fa
